# Generated by Django 4.0.1 on 2022-02-23 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('answer', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='user_additional_detail',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(max_length=500)),
                ('mobile_number', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profileimg')),
                ('clinic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_patient', models.BooleanField(default=False)),
                ('is_lab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100)),
                ('report_name', models.CharField(max_length=100)),
                ('reffered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('lab_name', models.CharField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('lab_mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('report_file_name', models.CharField(max_length=50)),
                ('report_upload', models.FileField(upload_to='reports')),
                ('report_img_name', models.CharField(max_length=100, null=True)),
                ('report_image', models.ImageField(blank=True, null=True, upload_to='reports/img')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('question', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('report_id', 'lab_name'), name='unique_report_lab_report_id'),
        ),
    ]
