# Generated by Django 4.0.1 on 2022-02-27 07:37

import Apps.fileValidator
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_upload',
            field=models.FileField(upload_to='reports', validators=[Apps.fileValidator.FileValidator(allowed_extensions=('pdf', 'doc', 'docx'), max_size=2097152)]),
        ),
        migrations.AlterField(
            model_name='user_additional_detail',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Replace Initial 0 with Country Code', max_length=128, region=None),
        ),
    ]
